<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" ignored="0" name="FREE CRM Test" tests="1" failures="1" timestamp="21 Sep 2020 14:47:52 GMT" time="1.096" errors="0">
  <testcase name="feature" time="0.366" classname="com.qa.testrunner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.NullPointerException">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.qa.testrunner.TestRunner.feature(TestRunner.java:42)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at com.qa.base.TestBase.initialization(TestBase.java:63)
at com.qa.stepDefinition.LoginPageSteps.user_is_already_on_Login_Page(LoginPageSteps.java:50)
at âœ½.Given user is already on Login Page(D:/BDDTestNG/src/main/java/com/qa/feature/Login.feature:6)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- FREE CRM Test -->
